---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.authelia.com
      chart: authelia
      version: 0.8.57
      sourceRef:
        kind: HelmRepository
        name: authelia-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    domain: "${SECRET_DOMAIN}"
    image:
      registry: docker.io
      repository: authelia/authelia
      tag: 4.37.5
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/configuration-snippet: |
          # https://www.authelia.com/docs/security/measures.html
          add_header Cache-Control "no-store";
          add_header Pragma "no-cache";
          add_header X-Frame-Options "SAMEORIGIN";
          add_header X-XSS-Protection "1; mode=block";
      className: nginx
      subdomain: auth
      tls:
        enabled: true
        secret: "authelia.tls"
    pod:
      strategy:
        type: Recreate
      env:
        - name: TZ
          value: ${TIMEZONE}
      extraVolumeMounts:
        - name: config-custom
          mountPath: /config
      extraVolumes:
        - name: config-custom
          configMap:
            name: authelia-config-custom
            items:
              - key: users_database.yml
                path: users_database.yml
      resources:
        requests:
          memory: 200Mi
          cpu: 150m
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        memory: 128Mi
    configMap:
      default_redirection_url: "https://start.${SECRET_DOMAIN}"
      theme: auto
      enabled: true
      authentication_backend:
        disable_reset_password: true
        ldap:
          enabled: false
        file:
          enabled: true
          path: /config/users_database.yml
          password:
            algorithm: argon2
            argon2:
              variant: argon2id
              iterations: 3
              key_length: 32
              salt_length: 16
              memory: 65536
              parallelism: 8
      access_control:
        networks:
          - name: private
            networks:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
        rules:
          - domain:
              - auth.${SECRET_DOMAIN}
              - login.${SECRET_DOMAIN}
            policy: bypass
          - domain: "*.${SECRET_DOMAIN}"
            policy: one_factor
            subject:
              - "group:admins"
      session:
        expiration: 4h
        inactivity: 30m
        remember_me_duration: 1M
        redis:
          enabled: true
          enabledSecret: true
          username: ""
          host: redis.databases.svc.cluster.local
          database_index: 0
          sentinel_name: redis-master

      storage:
        local:
          enabled: false
        mysql:
          enabled: false
        postgres:
          enabled: true
          username: ${SECRET_AUTHELIA_POSTGRES_USERNAME}
          database: ${SECRET_AUTHELIA_POSTGRES_DATABASE}
          host: postgres-rw.databases.svc.cluster.local

      notifier:
        smtp:
          enabled: true
          enabledSecret: true
          host: ${SECRET_SMTP_HOST}
          port: 587
          timeout: 5s
          username: ${SECRET_SMTP_USERNAME}
          password: ${SECRET_SMTP_PASSWORD}
          sender: "auth@${SECRET_DOMAIN}"
          ## HELO/EHLO Identifier. Some SMTP Servers may reject the default of localhost.
          identifier: ${SECRET_DOMAIN}
          ## Subject configuration of the emails sent.
          ## {title} is replaced by the text from the notifier
          subject: "[Authelia] {title}"
          ## This address is used during the startup check to verify the email configuration is correct.
          ## It's not important what it is except if your email server only allows local delivery.
          startup_check_address: ${SECRET_SMTP_USER}
          disable_require_tls: false
          disable_html_emails: false

    secret:
      storage:
        key: STORAGE_PASSWORD
        value: ${SECRET_AUTHELIA_POSTGRES_PASSWORD}
        filename: STORAGE_PASSWORD
      jwt:
        key: JWT_TOKEN
        value: ${SECRET_AUTHELIA_JWT_SECRET}
        filename: JWT_TOKEN
      redis:
        key: REDIS_PASSWORD
        value: ${SECRET_AUTHELIA_REDIS_PASSWORD}
        filename: REDIS_PASSWORD
      smtp:
        key: SMTP_PASSWORD
        value: ${SECRET_SMTP_PASSWORD}
        filename: SMTP_PASSWORD
      storageEncryptionKey:
        key: STORAGE_ENCRYPTION_KEY
        value: ${SECRET_AUTHELIA_STORAGE_ENCRYPTION_KEY}
        filename: STORAGE_ENCRYPTION_KEY
