---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hubblo-org-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://raw.githubusercontent.com/hubblo-org/scaphandre/main/helm/
  timeout: 3m