---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia-charts.yaml
  - authentik.yaml
  - backube-charts.yaml
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - cilium-charts.yaml
  - cloudnative-pg-charts.yaml
  - coredns-charts.yaml
  - csi-driver-nfs-charts.yaml
  - dandydev-charts.yaml
  - descheduler-charts.yaml
  - dysnix-charts.yaml
  - emberstack-charts.yaml
  - external-dns-charts.yaml
  - gitea-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - infracloudio-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack.yaml
  - k8s-at-home.yaml
  - k8s-gateway-charts.yaml
  - kasten-charts.yaml
  - kubernetes-sigs-nfd-charts.yaml
  - kyverno-charts.yaml
  - longhorn-charts.yaml
  - metallb-charts.yaml
  - project-calico-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - vector-charts.yaml
  - victoria-metrics-charts.yaml
  - vmware-tanzu.yaml
  - weave-gitops-charts.yaml
