f---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.19.5
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 3
    serviceType: LoadBalancer
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
    service:
      externalTrafficPolicy: Cluster
      loadBalancerIP: ${SVC_COREDNS_ADDR}
      clusterIP: 10.43.0.10 # default coreDNS IP for k3s
      annotations:
        metallb.universe.tf/allow-shared-ip: coredns
        metallb.universe.tf/address-pool: "home-network"
    rbac:
      create: true
    isClusterService: true
    zoneFiles:
      - filename: ${SECRET_DOMAIN}
        domain: ${SECRET_DOMAIN}
        contents: |
          ${SECRET_DOMAIN}.   IN SOA etta.ns.cloudflare.com. dns.cloudflare.com. 2020100600 10000 2400 604800 3600
          ${SECRET_DOMAIN}.   IN A ${SECRET_HOME_IP}
          *.${SECRET_DOMAIN}.   IN CNAME ${SECRET_DOMAIN}.
    servers:
      - zones:
          - zone: .
            scheme: dns://
        port: 53
        plugins:
          # - name: log
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . ${SECRET_GATEWAY_IP}
            configBlock: |-
              except ${SECRET_DOMAIN} *.${SECRET_DOMAIN}
          - name: file
            parameters: /etc/coredns/${SECRET_DOMAIN} ${SECRET_DOMAIN}
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
