---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
      version: 1.15.6
  interval: 30m

  values:
    autoDirectNodeRoutes: true
    bandwidthManager:
      enabled: true
      bbr: true
    bpf:
      masquerade: true
    cluster:
      name: kubernetes
      id: 1

    # choose between bgp or l2announcements
    bgpControlPlane:
      enabled: true
    l2announcements:
      enabled: false
      # enabled: true
      # leaseDuration: 120s
      # leaseRenewDeadline: 60s
      # leaseRetryPeriod: 1s

    containerRuntime:
      integration: containerd
      socketPath: /var/run/k3s/containerd/containerd.sock
    endpointRoutes:
      enabled: true
    hubble:
      serviceMonitor:
        enabled: true

      dashboards:
        enabled: true
        label: grafana_dashboard
        namespace: monitoring
        labelValue: "1"
        annotations: {}

      relay:
        enabled: true
        prometheus:
          serviceMonitor:
            enabled: true

      ui:
        enabled: true
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/auth-method: GET
            nginx.ingress.kubernetes.io/auth-url: http://stupid-auth.security.svc.cluster.local:8000/auth
            nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/login?rd=$scheme://$best_http_host$request_uri
            nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
            nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
          hosts:
            - &host hubble.${SECRET_DOMAIN}
          tls:
            - hosts:
                - *host
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: ${NET_POD_CIDR}
    k8sServiceHost: ${SVC_K8S_ADDR}
    k8sServicePort: 6443
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

    loadBalancer:
      algorithm: maglev
      mode: dsr
    localRedirectPolicy: true
    operator:
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
    rollOutCiliumPods: true
    securityContext:
      privileged: true
    tunnel: disabled
