apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert
  namespace: monitoring
spec:
  replicaCount: 1
  datasource:
    url: "http://vmsingle-vmsingle:8429/select/0/prometheus/"
  notifier:
    url: "http://alertmanager.monitoring.svc:9093"
  remoteWrite:
    url: "http://vmsingle-vmsingle:8429/insert/0/prometheus/"
  remoteRead:
    url: "http://vmsingle-vmsingle:8429/select/0/prometheus/"
  evaluationInterval: "30s"
  selectAllByDefault: true
