apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert
  namespace: monitoring
spec:
  replicaCount: 1
  datasource:
    url: "http://vmsingle-vmsingle:8429/prometheus/"
  notifier:
    url: "http://alertmanager.monitoring.svc:9093"
  remoteWrite:
    url: "http://vmsingle-vmsingle:8429/"
  remoteRead:
    url: "http://vmsingle-vmsingle:8429/prometheus/"
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      memory: 100Mi
  evaluationInterval: "30s"
  selectAllByDefault: true
