apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle
  namespace: monitoring
spec:
  # Add fields here
  retentionPeriod: "4"
  storage:
    storageClassName: longhorn
    accessModes: 
      - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
