
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-snmp-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-snmp-exporter
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: snmp-exporter
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: snmp-exporter
        readOnly: true
        defaultMode: 420
    resources:
      requests:
        cpu: 10m
      limits:
        memory: 100Mi
    serviceMonitor:
      enabled: true
      namespace: monitoring
      # selector:
      #   prometheus: prometheus
      params:
        - name: hexpoe
          target: ${SECRET_GATEWAY_IP}
          module:
            - mikrotik
      path: /snmp
      scrapeTimeout: 30s
