apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster/helm-release.yaml
- cluster/secret.enc.yaml
- cluster/hr-v3.yaml
- helm-release.yaml
- scheduled-backup/helm-release.yaml
- scheduled-backup/secret.enc.yaml
- pgdump/helm-release.yaml
- pgdump/pvc.yaml
- pgdump/backup.yaml
