---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: cloudflare-creds
            key: cloudflare_api_email
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-creds
            key: cloudflare_api_token
    extraArgs:
      - --ingress-class=external
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
    policy: sync
    sources: ["crd", "ingress"]
    txtOwnerId: homelab
    txtPrefix: k8s.
    domainFilters:
      - "${SECRET_DOMAIN}"
      - "${SECRET_DOMAIN_OUTSIDE}"
    logLevel: info
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: cloudflare-creds
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 100Mi
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"