---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 6.12.2
      sourceRef:

        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    nameOverride: external-dns
    sources:
      - ingress
    provider: cloudflare
    interval: 5m
    logLevel: debug
    cloudflare:
      secretName: cloudflare-creds
      proxied: true
    policy: sync
    domainFilters:
      - "${SECRET_DOMAIN}"
      - "${SECRET_DOMAIN_OUTSIDE}"
    zoneIdFilters:
      - "${SECRET_INGRESS_ZONE_ID}"
      - "${SECRET_DOMAIN_OUTSIDE_ZONE_ID}"
    crd:
      create: true
    txtPrefix: "k8s."
    # annotationFilter: "external-dns/is-public in (true)"
    resources:
      requests:
        memory: 100Mi
        cpu: 25m