---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.14.3
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-creds
            key: cloudflare_api_token
    extraArgs:
      - --cloudflare-proxied
      # - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      # - --crd-source-kind=DNSEndpoint
      - --zone-id-filter=${SECRET_INGRESS_ZONE_ID}
      - --zone-id-filter=${SECRET_DOMAIN_OUTSIDE_ZONE_ID}
    policy: sync
    sources: ["ingress"]
    txtOwnerId: homelab
    txtPrefix: k8s.
    domainFilters:
      - "${SECRET_DOMAIN}"
      - "${SECRET_DOMAIN_OUTSIDE}"
    logLevel: info
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: cloudflare-creds
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 100Mi
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"