apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:RUYQm+RABN1bDOuU3Y+RfiFA5m7HJQrEAq6xJ8j905hqN9gIgbs/GQ==,iv:HM+QGb0rrJv3L0kzeJtfxdKXyVaRq8cnoQD7TC3jd38=,tag:1tG1l+R00tTSfo51y0YlKg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ydepnmnqfu5au0rcv888flh6f9h8cxf2scyf8ddunemrw82kcstsv8ks5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YngzVTFWdDB6YXJTaFdX
            TG9na0dPelV2azQ4KzZ1V1g2ZjNpc2xPVmhVClFNaDZTTjlrMEQvYUJKTDNXWGx4
            Zk9Uc0JXVkExSkpyRWQ5aUJ3SFU2VUEKLS0tIFpLQmJ6QS9vUk9wclVtRVhuMUpa
            bm9OVlUzazFRajJDaHJ5dnFtdUtjQWMKtOyJvbmWbReshyR3ft7z7QbHFgw0FvKw
            kWaY3JuQZW05F1NXhnI+ltnVSYQRI+Z77cpJDee6jcHm/tpeRvZjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T18:23:43Z"
    mac: ENC[AES256_GCM,data:qS5LRt5J1YpUK7lUfVCZH0S6z6tGrEHzd9D/Coa7cRB3Wvvb7vD6diH46JYRzYKGtDKGDYqvJONqaGv4DkLh42bQkAs/renr6fnPQT5/HEhEo11z9NgpjVuPfIIu3iGko/NSXY9knjDhLd5MzmihJseT5omk4LGULfejBpnhqcg=,iv:WMi520CvwuFepnNKfjIYvjhfUcYJS8QGTbvGmSWWmTo=,tag:4p0MZYXx6GdiqRb4+J1v0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
