apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    cloudflare_api_email: ENC[AES256_GCM,data:JwMMq+9+x+xWABMa7RI=,iv:Xrd9T6oS/rHLCAxQvdLHEtxMOVl2A6e2qMltNNfLzGI=,tag:ioJdCS/g9+MRIUabwOopOQ==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:aFBwbrTvv1hmoB1AXETha2pG/OlDGYPaZZPNMeIR3v27hSGEYhN53A==,iv:b8OiHdM5OsueT3eWL3L8xWhEE+trUcQOD4jtNxnF3/Q=,tag:N1ed+qD+jAHyRAfdya1UOQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ydepnmnqfu5au0rcv888flh6f9h8cxf2scyf8ddunemrw82kcstsv8ks5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YngzVTFWdDB6YXJTaFdX
            TG9na0dPelV2azQ4KzZ1V1g2ZjNpc2xPVmhVClFNaDZTTjlrMEQvYUJKTDNXWGx4
            Zk9Uc0JXVkExSkpyRWQ5aUJ3SFU2VUEKLS0tIFpLQmJ6QS9vUk9wclVtRVhuMUpa
            bm9OVlUzazFRajJDaHJ5dnFtdUtjQWMKtOyJvbmWbReshyR3ft7z7QbHFgw0FvKw
            kWaY3JuQZW05F1NXhnI+ltnVSYQRI+Z77cpJDee6jcHm/tpeRvZjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T14:58:50Z"
    mac: ENC[AES256_GCM,data:w1VxRlv2BOLzVB6iJnp3iYcdo/784+jA1Yox1r7QLM2OyHapKwzrSilL9zbe6TTSZJyX1jNl6gcUDX6IBukmOcXLYt/TqniHEzyXqTI300sc4xAToiE+2laICB3JBMr3daSq0/oYSlby8/h/FR/2Y8wCmEbeC2E7aHuBvckzFwM=,iv:Rw+qG8bG+2+nXQNEACdKkNQQGifiLlCmKVukGnRUEYc=,tag:1ZbkMaWaY0z55/f33iBwNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
