apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:aFBwbrTvv1hmoB1AXETha2pG/OlDGYPaZZPNMeIR3v27hSGEYhN53A==,iv:b8OiHdM5OsueT3eWL3L8xWhEE+trUcQOD4jtNxnF3/Q=,tag:N1ed+qD+jAHyRAfdya1UOQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ydepnmnqfu5au0rcv888flh6f9h8cxf2scyf8ddunemrw82kcstsv8ks5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YngzVTFWdDB6YXJTaFdX
            TG9na0dPelV2azQ4KzZ1V1g2ZjNpc2xPVmhVClFNaDZTTjlrMEQvYUJKTDNXWGx4
            Zk9Uc0JXVkExSkpyRWQ5aUJ3SFU2VUEKLS0tIFpLQmJ6QS9vUk9wclVtRVhuMUpa
            bm9OVlUzazFRajJDaHJ5dnFtdUtjQWMKtOyJvbmWbReshyR3ft7z7QbHFgw0FvKw
            kWaY3JuQZW05F1NXhnI+ltnVSYQRI+Z77cpJDee6jcHm/tpeRvZjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T15:06:15Z"
    mac: ENC[AES256_GCM,data:4dF+pS/HYfd5uN7UoAMw0omvLk6VhMyu8YQpKeE8+XO4XXJp0Q1iUZNML9i56/IL2M9JcJIyC9WvagN9PTpsbzU1ObxOH9X9qMpNoZa/WFAnVtkVeKvgd5czBgDJF7YVXUiq4ulATkkdc3kpG3+H5jILW6c4S4AJJ8bKakA2Y0I=,iv:oKe/dNzxy0KShqC1A/x7+LNZh1ARbK2o9dal8oM7qtc=,tag:aIIr1uPB0t8xEr0g0Ux1fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
