---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-state-metrics
      version: 5.15.3
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  values:
    fullnameOverride: kube-state-metrics
    releaseLabel: false # disable for victoria-metrics
    resources:
      requests:
        cpu: 10m
      limits:
        memory: 100Mi
    metricLabelsAllowlist:
      - deployments=[*]
      - persistentvolumeclaims=[*]
      - pods=[*]
    prometheus:
      monitor:
        enabled: true
        honorLabels: true
        relabelings:
          - action: replace
            regex: ^(.*)$
            replacement: $1
            sourceLabels: ["__meta_kubernetes_pod_node_name"]
            targetLabel: kubernetes_node
