apiVersion: v1
kind: Secret
metadata:
  name: restic-config-backup-postgresql-dump
  namespace: databases
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${BACKUP_RESTIC_PATH}/postgresql-dump
  RESTIC_PASSWORD: ${SECRET_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${SECRET_RESTIC_AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${SECRET_RESTIC_AWS_SECRET_ACCESS_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: postgresql-dump-backup
  namespace: databases
spec:
  sourcePVC: postgres-cluster-dump
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Clone
    pruneIntervalDays: 14
    repository: restic-config-backup-postgresql-dump
    storageClassName: longhorn
    volumeSnapshotClassName: longhorn
    retain:
      daily: 10
      weekly: 4
      monthly: 2
      yearly: 1
