---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-pgdump
  namespace: &namespace databases
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: postgres-cluster
      namespace: databases
  values:
    resources:
      - apiVersion: batch/v1
        kind: CronJob
        metadata:
          name: postgres-dump
        spec:
          schedule: "0 12 * * *"
          jobTemplate:
            spec:
              backoffLimit: 0
              template:
                spec:
                  containers:
                    - name: dump
                      image: postgres:14.7-alpine
                      volumeMounts:
                        - name: data
                          mountPath: /backup
                      args:
                        - pg_dumpall
                        - "-f"
                        - "/backup/postgres.pgdump"
                        - "-v"
                        - "-h"
                        - "postgres-ro"
                        - "-U"
                        - "postgres"
                      env:
                        - name: PGPASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: postgres-superuser
                              key: password
                  restartPolicy: Never
                  volumes:
                    - name: data
                      persistentVolumeClaim:
                        claimName: postgres-cluster-dump
