---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-cluster-dump
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 70Gi

  storageClassName: longhorn
