kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ClzB4PjusqgELt+lrZ7HRQ==,iv:P2W+rqvYQTbeHvZsOnq0VZxt/YGyylieq+dfY0NAB6A=,tag:m/pEYURni64xuxBl1LOxmg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:DfQkP8aK/ETkH5pEq2cEjsF5g24iHZSWkU+7fwMmSGk=,iv:+5dqHquPZIzAjAJgjZWzuYMqxxPR+rudTof1CE1HUiw=,tag:0eELzVMsOqrt9CeRaqp1bQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ydepnmnqfu5au0rcv888flh6f9h8cxf2scyf8ddunemrw82kcstsv8ks5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUFIxQStPTVpHbGg0TzRH
            MkszaTNjSUdRcm9OOGN2NWh5OXB1eTVHeDNjCjc1MVVIT1lFSnhPM2Z1czhqNE1B
            TEpUQkJqano2eXhtV2svWUtMODFjdG8KLS0tIGowSXE2SHVzV3BGaEFvaTBDdThD
            REdDaS9NUmY1bHBMVG9vZk0xT2ZVYVkKUq7kQ4EMSexa2Z0B7S5wX8VdjiW/XnlK
            f98WuKmy6RNg/SgHTzxuHj35AYmrkdHKoGlqoBX8X0+KteOQKbVpwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-10T12:04:33Z"
    mac: ENC[AES256_GCM,data:73lNDnCnJrdhArKnC1ogo8Qu3LrpNYHkOsVGrG2Q+qoIBxDeLeyJAW2OQIDWWDOKtc3rwc486fEoonuxbPj26J0s5EBimtc9ztctSJ2gHunS3Vx/Toce+HkC++oy3Kd2+eMB5GK4nRcuqEqNXSZKpxHWYwGraQ9h50UVY34FH18=,iv:hiuA5zIbP35Y1NNfiaP4MeFpWec8L+fcByKlZZ6HsZ4=,tag:yIW3Yze/O+aDFLh8vaJlkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
