---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: zigbee-device
spec:
  rules:
    - # Sonoff_Zigbee_3.0_USB_Dongle_Plus
      name: zigbee.sonoff
      labels:
        zigbee.feature.node.kubernetes.io/sonoff: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["10c4", "ea60"] }