---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 17.3.18
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    architecture: replication
    auth:
      enabled: true
      sentinel: true
      password: "${SECRET_AUTHELIA_REDIS_PASSWORD}"
    replica:
      persistence:
        enabled: false
    sentinel:
      enabled: true
      masterSet: redis-master
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true