apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: kube-system
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:bOJ0b1nLtQjcmpWAp4MqMwp3EeaH9qDSiPI7rkPfIRYgma6Qw+Kmcw==,iv:/WwXWn2z3HNRbkfH4tcZCXjOs4F4yk/WUply5tWV5pQ=,tag:WlpGLrHfIYvDvHZiFremyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ydepnmnqfu5au0rcv888flh6f9h8cxf2scyf8ddunemrw82kcstsv8ks5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldy9UQ0FqT3owSUpWV2t3
            N2dsMmsrY1FpUTBUM3BGZzF1RHFaaFJyV0VrClpTeTdnSlM3S1I1YUFzNTJBRkh0
            UHNZaVdJZVk1alBNNnNhK0gwRUxabzQKLS0tIGdHQXFtRVFBdVdRNENGYlRQcTJj
            NEhzSVBqdTJSRFFEQzREOVZzM00vT3MKbEh9v5csDDSXbKTfJevgN7Jxy7BNT7HC
            DmAAAZdRozfCwPcsx+kJuIync7XZ2RWjvnqDCvBoqPRpJhG5pVO8DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-05T19:23:11Z"
    mac: ENC[AES256_GCM,data:SKaXOLrNhZnsdghOnV10AZ6AABVyelvSFD6Wd5RL9zRcQFTyReU/V+Z9QLboPx6+bOs/fEGGA249DP9dtx8SFEgSXwu5cY9oOn8frI69J4PUcXHwGKm54Xevw/rQZbNMXtfuCgZlzcFws09P1mg25py5a8HKoXH3Fp+OMByyMA0=,iv:yWMEJtahULqG9otccV4KIQoSE5qGoP5Fv/W5V0yhDiA=,tag:nJbGBeyC3VhOVa+QNuAeLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
