---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-prod
  namespace: kube-system
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: ${SECRET_ZERO_KEY_ID}
      keySecretRef:
        name: zerossl-eab
        key: secret
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: zerossl-prod
    solvers:
      - dns01:
          cloudflare:
            email: ${SECRET_ADMIN_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
