---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb/
      chart: metallb
      version: 0.13.9
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
    prometheus:
      # serviceAccount: metallb-prometheus
      podMonitor:
        enabled: false
      prometheusRule:
        enabled: false
    speaker:
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
      frr:
        enabled: false
        # image:
        #   repository: docker.io/frrouting/frr
        #   tag: v8.2.2
