---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: k8s-gateway
      version: 1.1.15
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: k8s-gateway
    domain: ${SECRET_DOMAIN}
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      loadBalancerIP: "${SVC_K8S_GATEWAY_ADDR}"
      externalTrafficPolicy: Local
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi