

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-config
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: metallb
      namespace: kube-system
  values:
    resources:
      - apiVersion: metallb.io/v1beta1
        kind: BGPAdvertisement
        metadata:
          name: bgp-lb
          namespace: kube-system
        spec:
          ipAddressPools:
            - home-network
          peers:
            - mikrotik
      - apiVersion: metallb.io/v1beta2
        kind: BGPPeer
        metadata:
          name: mikrotik
          namespace: kube-system
        spec:
          peerAddress: ${SECRET_GATEWAY_IP}
          peerASN: 65530
          myASN: 64512
          holdTime: 1m30s
      - apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: external-ip
          namespace: kube-system
        spec:
          addresses:
          - ${SECRET_HOME_IP}/32
      - apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: home-network
          namespace: kube-system
        spec:
          addresses:
            - ${NET_HOME_CIDR}